name: The workflow number 1
on:
  workflow_dispatch:

jobs:
  job-not-in-a-container:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo ${{ job.container }}
  job-in-a-container:
    runs-on: ubuntu-latest
    container: debian:latest
    steps:
      - shell: bash
        run: echo ${{ job.container }}
